import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      status: 'admin'
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      status: 'member',
    },
  ],
  products: [
    {
      name: 'Avocado, Large',
      tags: ['vegetables'],
      image: '/assets/veges/avocado.png',
      price: .69,
      stock: 10,
      desc: '1 ct',

    },
    {
      name: 'Cucumbers',
      tags: ['vegetables'],
      image: '/assets/veges/Cucumbers.png',
      price: 120,
      stock: 10,
      desc: '1 ct',

    },
    {
      name: 'Green Bell Pepper',
      tags: ['vegetables'],
      image: '/assets/veges/GreenBellPepper.webp',
      price: .39,
      stock: 10,
      desc: '1 ct',

    },
    {
      name: 'Onion Red',
      tags: ['vegetables'],
      image: '/assets/veges/OnionRed.webp',
      price: 1.09,
      stock: 10,
      desc: '1 ct',
    },
    {
      name: 'Eggplant',
      tags: ['vegetables'],
      image: '/assets/veges/Eggplant.webp',
      price: 1.19,
      stock: 10,
      desc: '1 ct',
    },
    {
      name: 'Yams Red',
      tags: ['vegetables'],
      image: '/assets/veges/yamsred.webp',
      price: .79,
      stock: 10,
      desc: '1 ct',
    },
    {
      name: 'Green Giant Fresh Carrots',
      tags: ['vegetables'],
      image: '/assets/veges/GreenGiantFreshCarrots.webp',
      price: .89,
      stock: 10,
      desc: '1 lb',
    },
    // fruits
    {
      name: 'Watermelons Seedless',
      tags: ['fruits'],
      image: '/assets/fruits/WatermelonsSeedless.png',
      price: 1.89,
      stock: 10,
      desc: '1 ct',
    },
    {
      name: 'Large Mangos',
      tags: ['fruits'],
      image: '/assets/fruits/mango.png',
      price: .89,
      stock: 10,
      desc: '1 ct',
    },
    {
      name: 'Honeydew',
      tags: ['fruits'],
      image: '/assets/fruits/honeydew.webp',
      price: 1.59,
      stock: 10,
      desc: '1 ct',
    },
    {
      name: 'Pears Bartlett',
      tags: ['fruits'],
      image: '/assets/fruits/PearsBartlett.webp',
      price: .89,
      stock: 10,
      desc: '1 ct',
    },
    {
      name: 'Sweet Limes',
      tags: ['fruits'],
      image: '/assets/fruits/SweetLimes.webp',
      price: .69,
      stock: 10,
      desc: '1 ct',
    },
    // meat
    {
      name: 'Chicken Breast Bnls Skinless',
      tags: ['meat'],
      image: '/assets/meat/chickenbreast.webp',
      price: 3.49,
      stock: 10,
      desc: '1 pkg',
    },
    {
      name: 'Chicken Drumsticks',
      tags: ['meat'],
      image: '/assets/meat/chickendrumsticks.webp',
      price: 1.99,
      stock: 10,
      desc: '1 pkg',
    },
    {
      name: 'Buddig Original Deli Thin Beef',
      tags: ['meat'],
      image: '/assets/meat/BuddigOriginalDeliThinBeef.webp',
      price: .89,
      stock: 10,
      desc: '1 pkg',
    },
    {
      name: 'Chicken Thighs',
      tags: ['meat'],
      image: '/assets/meat/ChickenThighs.jpeg',
      price: 5.97,
      stock: 10,
      desc: '1 pkg',
    },
    {
      name: 'Cacique Pork Chorizo',
      tags: ['meat'],
      image: '/assets/meat/BuddigOriginalDeliThinBeef.webp',
      price: 1.19,
      stock: 10,
      desc: '1 pkg',
    },
    // dairy
    {
      name: 'Egglands Best Organic Cage Free Grade A Brown Eggs',
      tags: ['dairy'],
      image: '/assets/dairy/egglandegg.webp',
      price: 6.39,
      stock: 10,
      desc: '12 ct',
    },
    {
      name: 'Horizon Organic 2% Milk',
      tags: ['dairy'],
      image: '/assets/dairy/horizonmilk.webp',
      price: 4.99,
      stock: 10,
      desc: '1/2 gal',
    },
    {
      name: 'Yoplait Original Yogurt Harvest Peach Tub',
      tags: ['dairy'],
      image: '/assets/dairy/yoplaitorginalyogurtharvest.webp',
      price: 3.49,
      stock: 10,
      desc: '32 oz',
    },
    {
      name: 'Shamrock Farms Vitamin D Whole Milk',
      tags: ['dairy'],
      image: '/assets/dairy/shamrockfarmsvitamind.webp',
      price: 4.69,
      stock: 10,
      desc: '1 gal',
    },
    {
      name: 'Chobani Plain Non-Fat Greek Yogurt',
      tags: ['dairy'],
      image: '/assets/dairy/chobaniplannonfat.webp',
      price: 5.70,
      stock: 10,
      desc: '32 oz',
    },
    {
      name: 'Challenge Butter',
      tags: ['dairy'],
      image: '/assets/dairy/ChallengeButter.webp',
      price: 5.29,
      stock: 10,
      desc: '16 oz',
    },
    {
      name: 'SuperPretzel Baked Soft Pretzels',
      tags: ['frozen'],
      image: '/assets/frozen/superpretzel.webp',
      price: 4.09,
      stock: 10,
      desc: '6 ct',
    },
    {
      name: 'Kelloggs Eggo Waffles Homestyle',
      tags: ['frozen'],
      image: '/assets/frozen/kellogg.webp',
      price: 2.89,
      stock: 10,
      desc: '10 ct',
    },
    {
      name: 'Red Baron Pizzeria Style Classic Crust Pepperoni Pizza',
      tags: ['frozen'],
      image: '/assets/frozen/redbaronclassiccrust.webp',
      price: 4.09,
      stock: 10,
      desc: '20 oz',
    },
    {
      name: 'Cool Whip Original Whipped Topping',
      tags: ['frozen'],
      image: '/assets/frozen/coolwhip.webp',
      price: 4.69,
      stock: 10,
      desc: '16 oz',
    },
    {
      name: 'El Monterey Beef & Bean Burritos',
      tags: ['frozen'],
      image: '/assets/frozen/elmontererybeef.webp',
      price: 4.69,
      stock: 10,
      desc: '8 ct',
    },
    // pantry
    {
      name: 'Kraft Original Flavor Macaroni and Cheese',
      tags: ['pantry'],
      image: '/assets/pantry/kraft.webp',
      price: 1.49,
      stock: 10,
      desc: '7.25 oz',
    },
    {
      name: 'Rotel Original Diced Tomatoes & Green Chilies',
      tags: ['pantry'],
      image: '/assets/pantry/rotel.webp',
      price: 1.49,
      stock: 10,
      desc: '12 oz',
    },
    {
      name: 'Cinnamon Toast Crunch Cereal - General Mills',
      tags: ['pantry'],
      image: '/assets/pantry/cinnamon.webp',
      price: 5.79,
      stock: 10,
      desc: '19.3 oz',
    },
    {
      name: 'Jiffy Corn Muffin Mix - 8.5',
      tags: ['pantry'],
      image: '/assets/pantry/jiffy.webp',
      price: .89,
      stock: 10,
      desc: '8.5 oz',
    },
    {
      name: 'Jif Creamy Peanut Butter',
      tags: ['pantry'],
      image: '/assets/pantry/jifcreamypeanutbutter.webp',
      price: 3.29,
      stock: 10,
      desc: '16 oz',
    },
    {
      name: 'Heinz Easy Squeeze Tomato Ketchup',
      tags: ['pantry'],
      image: '/assets/pantry/heinz.webp',
      price: 3.79,
      stock: 10,
      desc: '20 oz',
    }
  ],
};
export default data;


